# Generated by Django 4.0.4 on 2022-04-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=32)),
                ('om', models.CharField(max_length=11)),
                ('pontszam', models.FloatField()),
                ('A_eredmeny', models.BooleanField()),
                ('B_eredmeny', models.BooleanField()),
                ('C_eredmeny', models.BooleanField()),
                ('D_eredmeny', models.BooleanField()),
                ('E_eredmeny', models.BooleanField()),
                ('F_eredmeny', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tanulo',
                'verbose_name_plural': 'Tanulok',
            },
        ),
    ]
